# Generated by Django 3.2.19 on 2023-10-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0042_auto_20230919_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='positivity',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], default='negative', help_text='Whether this is a positive or negative finding', max_length=24, verbose_name='Finding Positivity'),
        ),
    ]
