# Generated by Django 4.2 on 2024-10-25 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("target_id", models.PositiveIntegerField()),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("update", models.BinaryField()),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="history",
            index=models.Index(
                fields=["target_type", "target_id", "id"],
                name="collab_mode_target__72ac10_idx",
            ),
        ),
    ]
